### ISSUE TITLE
Parser must not allow add or override resources

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#176] opened 2016-07-22 01:47 UTC
```yaml
#%RAML 1.0
#api.raml
title: test

/resource:
  displayName: "Test"

```

```yaml

#%RAML 1.0 Overlay
title: Overlay2
extends: api.raml

/resource:
  displayName: "Test3"
/anotherResource:

```
**Actual result:**

No errors

**Expected result:**

An overlay adds or overrides nodes of a RAML API definition while **preserving its behavioral**, functional aspects. **Certain nodes of a RAML API definition specify the behavior of an API: its resources**, methods, parameters, bodies, responses, and so on

**Comment by svacas** [comment] 2016-07-25 03:44
I'm getting the following error with your example:
`"Invalid overlay node. Cannot override node: /anotherResource"`

**Comment by evangelina** [comment] 2016-07-26 20:11
I could reproduce it with the following RAML configuration:

```yaml
#%RAML 1.0
#input.raml
title: test

/resource:
  displayName: "Test"
```

```yaml
#%RAML 1.0 Overlay
title: Overlay
extends: input.raml

/resource:
  displayName: "Test2"
```

```yaml
#%RAML 1.0 Overlay
title: Overlay2
extends: input.raml

/resource:
  displayName: "Test3"
/anotherResource:
```

**Comment by evangelina** [comment] 2016-07-28 17:13
@svacas I could reproduce this issue with the latest changes

**Comment by evangelina** [comment] 2016-07-28 20:48
@eleonoraortega can we close this one? I can't reproduce it either.

**Closed** 2016-07-28 21:12 UTC
Labels: bug, invalid, major, v2
